import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  keyboardAvoid: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  scrollContent: {
    flexGrow: 1,
  },
  header: {
    backgroundColor: '#0F1714',
    paddingTop: 80,
    paddingBottom: 80,
    alignItems: 'center',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  brandContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  brandTitle: {
    fontFamily: 'serif',
    fontSize: 36,
    fontWeight: '800',
    color: '#84C9BA',
    fontStyle: 'italic',
  },
  underline: {
    width: 40,
    height: 2,
    backgroundColor: '#84C9BA',
    marginTop: 6,
  },
  tagline: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'serif',
    marginTop: 12,
    textAlign: 'center',
  },
  contentArea: {
    paddingHorizontal: 20,
    marginTop: -28,
  },
  googleCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    marginBottom: 16,
  },
  googleIconBox: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#1E2522',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  googleInnerSquare: {
    width: 12,
    height: 12,
    borderRadius: 2,
    backgroundColor: '#FFFFFF',
  },
  googleCardText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  phoneCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    padding: 18,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
    marginBottom: 20,
  },
  phoneHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  phoneIconBox: {
    backgroundColor: '#F0EDE8',
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  phoneIcon: {
    fontSize: 22,
    color: '#1A6B5A',
  },
  phoneHeaderTextContainer: {
    flex: 1,
  },
  phoneCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  phoneCardSubtitle: {
    fontSize: 13,
    color: '#6B7370',
    marginTop: 1,
  },
  phoneInputContainer: {
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 8,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginBottom: 16,
    backgroundColor: '#FAF8F4',
  },
  countryCodeText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1A1F1E',
  },
  verticalDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#E8E2D9',
    marginHorizontal: 12,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: '#1A1F1E',
    padding: 0,
  },
  sendOtpButton: {
    backgroundColor: '#0E5E4E',
    borderRadius: 100,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  sendOtpButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E8E2D9',
  },
  dividerText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 10,
    fontWeight: '700',
    color: '#6B7370',
    letterSpacing: 1.5,
    paddingHorizontal: 12,
  },
  infoCard: {
    backgroundColor: '#D4E8E3',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#C2DFD7',
  },
  compassCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0E5E4E',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  compassText: {
    fontSize: 16,
  },
  infoCardText: {
    fontSize: 13,
    color: '#1A6B5A',
    flex: 1,
    lineHeight: 18,
  },
  boldSage: {
    fontWeight: '700',
  },
  termsContainer: {
    alignItems: 'center',
    marginTop: 8,
    paddingBottom: 24,
  },
  termsText: {
    fontSize: 12,
    color: '#6B7370',
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 16,
  },
  termsLink: {
    color: '#1A6B5A',
    textDecorationLine: 'underline',
  },
  bottomBarIndicator: {
    width: 40,
    height: 3.5,
    backgroundColor: '#E8E2D9',
    borderRadius: 2,
    marginTop: 18,
  },
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
});

export default styles;
