import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  // Shared Header Styles
  headerWrapper: {
    height: 120,
    overflow: 'hidden',
    backgroundColor: '#0F1714',
  },
  headerBgImage: {
    width: '100%',
    height: '100%',
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  headerContent: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 28,
    paddingHorizontal: 24,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backBtnCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepText: {
    fontSize: 11,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  percentText: {
    fontSize: 11,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#E67E52',
  },
  progressBarContainer: {
    height: 4,
    marginTop: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFilled: {
    height: '100%',
    backgroundColor: '#E67E52',
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 48,
    backgroundColor: '#FAF8F4',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#6B7370',
    lineHeight: 20,
    marginBottom: 24,
  },
  sectionLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginTop: 24,
    marginBottom: 12,
  },
  sectionLabel: {
    fontSize: 9,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#6B7370',
    letterSpacing: 1.5,
  },
  maxPhotosInfo: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#6B7370',
  },
  // Photos Grid
  gridTip: {
    fontSize: 12,
    color: '#6B7370',
    marginBottom: 24,
    marginTop: 8,
  },
  // Photos Horizontal Scroll and Upload Tile
  horizontalScrollPhotos: {
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 8,
    marginBottom: 24,
  },
  photoSquareLarge: {
    width: 140,
    height: 140,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 12,
    position: 'relative',
  },
  photoSquareLargeDashed: {
    width: 140,
    height: 140,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#E8E2D9',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeBtnLarge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#D4704A',
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    zIndex: 10,
  },
  // Instagram Sync Card
  instaCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D4704A',
    borderRadius: 22,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  instaIconCol: {
    marginRight: 12,
    marginTop: 2,
  },
  instaContentCol: {
    flex: 1,
  },
  instaTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1F1E',
    marginBottom: 4,
  },
  instaBody: {
    fontSize: 12,
    color: '#6B7370',
    lineHeight: 18,
    marginBottom: 12,
  },
  instaBtn: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#D4704A',
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  instaBtnText: {
    color: '#D4704A',
    fontSize: 11,
    fontWeight: '700',
  },
  // Info banner
  infoBanner: {
    backgroundColor: '#E6F2EF',
    borderRadius: 22,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  infoIcon: {
    marginRight: 8,
    marginTop: 2,
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    color: '#1A6B5A',
    lineHeight: 18,
    fontWeight: '600',
  },
  // Button
  continueButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
