import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  // Top Bar
  topBar: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#0F1714',
  },
  topBarRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  backBtn: {
    padding: 4,
  },
  stepIndicator: {
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  percentText: {
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#D4704A',
  },
  progressBarContainer: {
    height: 4,
    backgroundColor: '#E8E2D9',
    borderRadius: 2,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  progressBarFilled: {
    height: '100%',
    backgroundColor: '#D4704A',
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 48,
    backgroundColor: '#FAF8F4',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#6B7370',
    lineHeight: 20,
    marginBottom: 24,
  },
  sectionLabel: {
    fontSize: 9,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#6B7370',
    letterSpacing: 1.5,
    marginBottom: 8,
    marginTop: 16,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 16,
    color: '#1A1F1E',
    fontSize: 15,
    marginBottom: 20,
  },
  multilineInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 12,
    height: 80,
    paddingHorizontal: 16,
    paddingTop: 12,
    color: '#1A1F1E',
    fontSize: 15,
    marginBottom: 20,
    textAlignVertical: 'top',
  },
  // Capacity row
  capacityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E2D9',
  },
  capacityRowTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  counterBtnMinus: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterBtnPlus: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#D4704A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterBtnTextMinus: {
    color: '#1A1F1E',
    fontSize: 18,
    fontWeight: 'bold',
  },
  counterBtnTextPlus: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  counterValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1F1E',
    marginHorizontal: 16,
    minWidth: 20,
    textAlign: 'center',
  },
  // Price
  priceTip: {
    fontSize: 12,
    color: '#6B7370',
    marginTop: -14,
    marginBottom: 20,
  },
  // Amenities grid 3 cols
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
    marginBottom: 20,
  },
  amenityCard: {
    width: '31%',
    margin: '1%',
    aspectRatio: 1,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  amenitySelected: {
    backgroundColor: '#F5E6D0',
    borderColor: '#D4704A',
  },
  amenityUnselected: {
    backgroundColor: '#F5F2EC',
    borderColor: '#E8E2D9',
  },
  amenityText: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  amenityTextSelected: {
    color: '#D4704A',
  },
  amenityTextUnselected: {
    color: '#1A1F1E',
  },
  // Button
  continueButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    marginTop: 8,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
