import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  topBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 48,
  },
  topBrandText: {
    color: '#84C9BA',
    fontSize: 16,
    fontFamily: 'serif',
    marginLeft: 6,
    fontWeight: '600',
  },
  checkmarkCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#D4704A',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '800',
    fontFamily: 'serif',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    color: '#84C9BA',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 40,
  },
  checklist: {
    width: '100%',
    paddingHorizontal: 16,
    marginBottom: 40,
  },
  checkrow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  checkCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#D4704A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  checkText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  button: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 52,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  laterText: {
    color: '#6B7370',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: '600',
    paddingVertical: 8,
  },
  footerNote: {
    color: '#6B7370',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 48,
    paddingHorizontal: 24,
  },
});
