import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 8 : 16,
    paddingBottom: 12,
    backgroundColor: '#0F1714',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E2B25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'serif',
  },
  editButton: {
    color: '#D4704A',
    fontSize: 15,
    fontWeight: '700',
  },
  editButtonText: {
    color: '#D4704A',
    fontSize: 15,
    fontWeight: '700',
  },
  scrollContent: {
    backgroundColor: '#FAF8F4',
    paddingBottom: 80,
  },
  statusBanner: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  statusBannerText: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  coverImage: {
    width: '100%',
    height: 220,
  },
  imagePlaceholder: {
    width: '100%',
    height: 220,
    backgroundColor: '#1A2B25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyName: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginTop: 16,
    marginHorizontal: 16,
    marginBottom: 4,
  },
  typeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  typeChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginLeft: 16,
  },
  typeChipText: {
    color: '#1A6B5A',
    fontSize: 11,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  locationText: {
    fontSize: 13,
    color: '#6B7370',
    marginHorizontal: 16,
    marginVertical: 4,
  },
  priceText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A6B5A',
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
  },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
  },
  statLabel: {
    fontSize: 9,
    color: '#6B7370',
    fontFamily: 'monospace',
    letterSpacing: 1,
    marginTop: 4,
    textAlign: 'center',
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  sectionLabel: {
    fontSize: 9,
    color: '#6B7370',
    fontFamily: 'monospace',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  detailItem: {
    marginBottom: 16,
  },
  detailItemLast: {
    marginBottom: 0,
  },
  detailValue: {
    fontSize: 15,
    color: '#1A1F1E',
    lineHeight: 20,
  },
  editInput: {
    backgroundColor: '#FAF8F4',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    color: '#1A1F1E',
    marginTop: 4,
  },
  editInputMultiline: {
    backgroundColor: '#FAF8F4',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    color: '#1A1F1E',
    marginTop: 4,
    height: 100,
    textAlignVertical: 'top',
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  amenityChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    backgroundColor: '#FFFFFF',
  },
  amenityChipSelected: {
    backgroundColor: '#E6F2EF',
    borderColor: '#1A6B5A',
  },
  amenityChipText: {
    fontSize: 12,
    color: '#6B7370',
  },
  amenityChipTextSelected: {
    color: '#1A6B5A',
    fontWeight: '700',
  },
  photosList: {
    paddingLeft: 0,
    gap: 8,
    marginTop: 8,
  },
  photoThumbnail: {
    width: 140,
    height: 90,
    borderRadius: 8,
    backgroundColor: '#E8E2D9',
  },
  noPhotosText: {
    fontSize: 13,
    color: '#6B7370',
    fontStyle: 'italic',
    marginTop: 8,
  },
  saveButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 100,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginBottom: 16,
  },
  cancelButtonText: {
    color: '#6B7370',
    fontSize: 16,
    fontWeight: '700',
  },
  bookingBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'ios' ? 90 : 76,
    backgroundColor: '#0F1714',
    borderTopWidth: 1,
    borderColor: '#1E2522',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 24 : 12,
    paddingTop: 12,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  priceValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  priceLabel: {
    fontSize: 12,
    color: '#6B7370',
    marginLeft: 4,
  },
  bookButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 48,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  instagramReelsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    gap: 10,
    marginBottom: 12,
    marginHorizontal: 16,
  },
  instagramReelsBtnText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  saveIconBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#1E2522',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rootLight: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  containerLight: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  topBarLight: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FAF8F4',
    paddingHorizontal: 16,
  },
  circleHeaderBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBarTitleLight: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
  },
  coverImageGuest: {
    width: '100%',
    height: 280,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  imageCounterBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  imageCounterText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  viewPhotosBtn: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 100,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  viewPhotosText: {
    color: '#1A1F1E',
    fontSize: 12,
    fontWeight: '700',
  },
  identitySection: {
    padding: 20,
  },
  nameRatingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  propertyNameGuest: {
    fontSize: 26,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    flex: 1,
    marginRight: 12,
    lineHeight: 32,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  ratingText: {
    fontSize: 14,
    color: '#1A1F1E',
    fontWeight: '700',
  },
  reviewCountText: {
    fontSize: 13,
    color: '#6B7370',
    marginLeft: 4,
  },
  typeBadge: {
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  typeBadgeText: {
    color: '#1A6B5A',
    fontSize: 10,
    fontWeight: '800',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
  },
  locationRowGuest: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  locationTextGuest: {
    fontSize: 14,
    color: '#6B7370',
    marginLeft: 6,
  },
  priceTagGuest: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginTop: 12,
  },
  amenityStrip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 20,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  amenityStripItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  amenityStripLabel: {
    fontSize: 11,
    color: '#6B7370',
    marginTop: 6,
    fontWeight: '600',
  },
  whyMatchesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    marginHorizontal: 20,
    marginBottom: 20,
  },
  whyMatchesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
  },
  whyMatchesTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
  },
  whyMatchesGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  whyMatchesGridItem: {
    width: '22%',
    alignItems: 'center',
  },
  whyMatchesIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F0EDE8',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  whyMatchesGridText: {
    fontSize: 10,
    color: '#1A1F1E',
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 14,
  },
  photosHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 12,
  },
  photosSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
  },
  viewAllPhotosLink: {
    fontSize: 13,
    color: '#1A6B5A',
    fontWeight: '700',
  },
  photosScrollView: {
    paddingLeft: 20,
    marginBottom: 20,
  },
  photoThumbnailGuest: {
    width: 150,
    height: 100,
    borderRadius: 12,
    marginRight: 12,
    backgroundColor: '#E8E2D9',
  },
  twoColumnSection: {
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  sideCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  sideCardTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#6B7370',
    fontFamily: 'serif',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  amenityGrid2Col: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  amenityCheckItem: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  checkText: {
    fontSize: 13,
    color: '#1A1F1E',
    fontWeight: '500',
  },
  pricingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  pricingLabel: {
    fontSize: 13,
    color: '#6B7370',
  },
  pricingValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  hostCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    marginHorizontal: 20,
    marginBottom: 140, // space above sticky bottom bar + floating nav
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  hostInfoCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    marginRight: 12,
  },
  hostAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#1A6B5A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hostAvatarText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  hostName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
  },
  superHostBadge: {
    backgroundColor: '#FDF2E9',
    borderRadius: 100,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignSelf: 'flex-start',
    marginVertical: 3,
  },
  superHostText: {
    color: '#D4704A',
    fontSize: 9,
    fontWeight: '800',
  },
  hostSmallText: {
    fontSize: 11,
    color: '#6B7370',
    marginTop: 1,
  },
  hostActionGroup: {
    flexDirection: 'row',
    gap: 10,
  },
  hostOutlineBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1A6B5A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stickyBottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E8E2D9',
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stickyPriceCol: {
    justifyContent: 'center',
  },
  stickyPriceText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
  },
  stickyPriceLabel: {
    fontSize: 12,
    color: '#6B7370',
    marginTop: 2,
  },
  stickyActionGroup: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  stickySaveBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bookNowBtn: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 48,
    paddingHorizontal: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bookNowText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  headerWrapper: {
    backgroundColor: '#021412',
    height: 100,
    position: 'relative',
    overflow: 'hidden',
  },
  headerAbsoluteImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.35,
    overflow: 'hidden',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 52 : 36,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'serif',
    letterSpacing: 0.5,
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FDF2E9',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginTop: 4,
    marginBottom: 8,
    marginLeft: 16,
  },
  rankingText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D4704A',
  },
  statSubLabel: {
    fontSize: 9,
    color: '#6B7370',
    marginTop: 2,
    textAlign: 'center',
  },
});
