import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 8 : 16,
    paddingBottom: 12,
    backgroundColor: '#0F1714',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E2B25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'serif',
  },
  editButton: {
    color: '#D4704A',
    fontSize: 15,
    fontWeight: '700',
  },
  editButtonText: {
    color: '#D4704A',
    fontSize: 15,
    fontWeight: '700',
  },
  scrollContent: {
    backgroundColor: '#FAF8F4',
    paddingBottom: 80,
  },
  statusBanner: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  statusBannerText: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  coverImage: {
    width: '100%',
    height: 220,
  },
  imagePlaceholder: {
    width: '100%',
    height: 220,
    backgroundColor: '#1A2B25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyName: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginTop: 16,
    marginHorizontal: 16,
    marginBottom: 4,
  },
  typeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  typeChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginLeft: 16,
  },
  typeChipText: {
    color: '#1A6B5A',
    fontSize: 11,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  locationText: {
    fontSize: 13,
    color: '#6B7370',
    marginHorizontal: 16,
    marginVertical: 4,
  },
  priceText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A6B5A',
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
  },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
  },
  statLabel: {
    fontSize: 9,
    color: '#6B7370',
    fontFamily: 'monospace',
    letterSpacing: 1,
    marginTop: 4,
    textAlign: 'center',
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  sectionLabel: {
    fontSize: 9,
    color: '#6B7370',
    fontFamily: 'monospace',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  detailItem: {
    marginBottom: 16,
  },
  detailItemLast: {
    marginBottom: 0,
  },
  detailValue: {
    fontSize: 15,
    color: '#1A1F1E',
    lineHeight: 20,
  },
  editInput: {
    backgroundColor: '#FAF8F4',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    color: '#1A1F1E',
    marginTop: 4,
  },
  editInputMultiline: {
    backgroundColor: '#FAF8F4',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    color: '#1A1F1E',
    marginTop: 4,
    height: 100,
    textAlignVertical: 'top',
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  amenityChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    backgroundColor: '#FFFFFF',
  },
  amenityChipSelected: {
    backgroundColor: '#E6F2EF',
    borderColor: '#1A6B5A',
  },
  amenityChipText: {
    fontSize: 12,
    color: '#6B7370',
  },
  amenityChipTextSelected: {
    color: '#1A6B5A',
    fontWeight: '700',
  },
  photosList: {
    paddingLeft: 0,
    gap: 8,
    marginTop: 8,
  },
  photoThumbnail: {
    width: 140,
    height: 90,
    borderRadius: 8,
    backgroundColor: '#E8E2D9',
  },
  noPhotosText: {
    fontSize: 13,
    color: '#6B7370',
    fontStyle: 'italic',
    marginTop: 8,
  },
  saveButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 100,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginBottom: 16,
  },
  cancelButtonText: {
    color: '#6B7370',
    fontSize: 16,
    fontWeight: '700',
  },
  bookingBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'ios' ? 90 : 76,
    backgroundColor: '#0F1714',
    borderTopWidth: 1,
    borderColor: '#1E2522',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 24 : 12,
    paddingTop: 12,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  priceValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  priceLabel: {
    fontSize: 12,
    color: '#6B7370',
    marginLeft: 4,
  },
  bookButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 48,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  instagramReelsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    gap: 10,
    marginBottom: 12,
    marginHorizontal: 16,
  },
  instagramReelsBtnText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  saveIconBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#1E2522',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
