import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#021412',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#FAF8F4',
    paddingBottom: 120,
  },
  headerWrapper: {
    backgroundColor: '#021412',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    position: 'relative',
  },
  headerAbsoluteImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.45,
  },
  headerContentContainer: {
    width: '100%',
    paddingTop: Platform.OS === 'ios' ? 60 : 48, // Immersive status bar offset
    paddingBottom: 32, // Compact space since banner is moved outside
    paddingHorizontal: 20,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    zIndex: 30,
  },
  greetingText: {
    fontSize: 14,
    color: '#84C9BA',
    fontFamily: 'serif',
    fontStyle: 'italic',
    letterSpacing: 0.5,
  },
  appTitle: {
    fontSize: 32,
    color: '#FFFFFF',
    fontWeight: '800',
    fontFamily: 'serif',
    marginTop: 2,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1A6B5A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#84C9BA',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  avatarText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  bannerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 16, // Premium padding
    paddingHorizontal: 22,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    marginHorizontal: 20, // Add horizontal margin since it's outside
    marginTop: -12, // Pull up to slightly overlap the rounded bottom of the hero by 12px
    marginBottom: 24,
    zIndex: 20,
  },
  bannerBadgeContainer: {
    alignSelf: 'flex-start',
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 10,
  },
  bannerBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#1A6B5A',
    letterSpacing: 1,
  },
  bannerContentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  bannerTextLeft: {
    flex: 1,
    marginRight: 12,
  },
  bannerTitle: {
    fontSize: 19, // Adjusted for reduced card height
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
    lineHeight: 25,
    marginBottom: 6,
  },
  bannerSubtitle: {
    fontSize: 11,
    color: '#6B7370',
    lineHeight: 16,
    marginBottom: 6,
  },
  bannerTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  bannerTag: {
    backgroundColor: '#FAF8F4',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  bannerTagText: {
    fontSize: 10,
    color: '#1A6B5A',
    fontWeight: '700',
  },
  bannerImage: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: '#F0EDE8',
  },
  bannerBtn: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    height: 44, // Adjusted for reduced card height
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  bannerBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  contentArea: {
    backgroundColor: '#FAF8F4',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
    letterSpacing: 0.3,
  },
  viewAllText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A6B5A',
  },
  horizontalScroll: {
    paddingLeft: 20,
    paddingRight: 8,
    paddingBottom: 24,
  },
  tripCard: {
    width: 180,
    height: 240,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    overflow: 'hidden',
    marginRight: 12,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  tripImage: {
    width: '100%',
    height: 110,
    backgroundColor: '#E6F2EF',
  },
  tripTextContainer: {
    padding: 12,
    flex: 1,
    justifyContent: 'space-between',
  },
  tripTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A1F1E',
    marginBottom: 2,
  },
  tripLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  tripLocation: {
    fontSize: 11,
    color: '#6B7370',
  },
  tripFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tripDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  tripDate: {
    fontSize: 9,
    color: '#6B7370',
    fontWeight: '600',
  },
  tripBadge: {
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  tripBadgeCompleted: {
    backgroundColor: '#E6F2EF',
  },
  tripBadgeUpcoming: {
    backgroundColor: '#FDF2E9',
  },
  tripBadgeText: {
    fontSize: 9,
    fontWeight: '700',
  },
  tripBadgeTextCompleted: {
    color: '#1A6B5A',
  },
  tripBadgeTextUpcoming: {
    color: '#D4704A',
  },
  momentCard: {
    width: 160,
    height: 160,
    borderRadius: 16,
    overflow: 'hidden',
    marginRight: 12,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  momentImageBg: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
  },
  momentOverlay: {
    padding: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  momentAuthor: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  momentLocation: {
    fontSize: 9,
    color: '#E8E2D9',
  },
  trendingCard: {
    width: 160,
    height: 200,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    overflow: 'hidden',
    marginRight: 12,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  trendingImage: {
    width: '100%',
    height: 110,
    backgroundColor: '#E6F2EF',
  },
  ratingBadge: {
    position: 'absolute',
    right: 8,
    top: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  ratingText: {
    fontSize: 9,
    color: '#1A1F1E',
    fontWeight: '700',
  },
  trendingInfo: {
    padding: 10,
  },
  trendingName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#1A1F1E',
  },
  trendingState: {
    fontSize: 10,
    color: '#6B7370',
  },
  bottomSpacer: {
    height: 48,
  },
});

export default styles;
