import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1714', // Deep Dark Green Header bleed background
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#FAF8F4', // Premium Cream content background
    paddingBottom: 80,
  },
  header: {
    backgroundColor: '#0F1714',
    paddingTop: Platform.OS === 'ios' ? 8 : 16,
    paddingBottom: 36,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  greetingText: {
    fontSize: 14,
    color: '#84C9BA',
    fontWeight: '600',
    fontFamily: 'serif',
    fontStyle: 'italic',
    letterSpacing: 0.5,
  },
  appTitle: {
    fontSize: 28,
    color: '#FFFFFF',
    fontWeight: '800',
    fontFamily: 'serif',
    marginTop: 2,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1A6B5A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#84C9BA',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  avatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  bannerCard: {
    backgroundColor: '#1E2B25',
    borderWidth: 1,
    borderColor: '#2D3F37',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  bannerBadgeContainer: {
    alignSelf: 'flex-start',
    backgroundColor: '#0E5E4E',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginBottom: 12,
  },
  bannerBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#84C9BA',
    letterSpacing: 1,
  },
  bannerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'serif',
    lineHeight: 26,
    marginBottom: 6,
  },
  bannerSubtitle: {
    fontSize: 13,
    color: '#A0A5A3',
    lineHeight: 18,
    marginBottom: 16,
  },
  bannerBtn: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  bannerBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  contentArea: {
    paddingTop: 28,
    backgroundColor: '#FAF8F4',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
    letterSpacing: 0.3,
  },
  viewAllText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A6B5A',
    textDecorationLine: 'underline',
  },
  horizontalScroll: {
    paddingLeft: 20,
    paddingRight: 8,
    paddingBottom: 24,
  },
  tripCard: {
    width: 220,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  tripEmojiCircle: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#F0EDE8',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  tripEmoji: {
    fontSize: 22,
  },
  tripTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1F1E',
    marginBottom: 3,
  },
  tripLocation: {
    fontSize: 12,
    color: '#6B7370',
    marginBottom: 12,
  },
  tripDivider: {
    height: 1,
    backgroundColor: '#F0EDE8',
    marginBottom: 12,
  },
  tripFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tripDate: {
    fontSize: 10,
    color: '#6B7370',
    fontWeight: '500',
  },
  tripBadge: {
    backgroundColor: '#E6F2EF',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  tripBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#1A6B5A',
  },
  momentCard: {
    width: 180,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    overflow: 'hidden',
    marginRight: 12,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  momentImageContainer: {
    height: 110,
    backgroundColor: '#E6F2EF',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  momentImgEmoji: {
    fontSize: 40,
  },
  momentLikeBadge: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    backgroundColor: 'rgba(26, 31, 30, 0.65)',
    borderRadius: 100,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  momentLikeText: {
    fontSize: 9,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  momentMeta: {
    padding: 12,
  },
  momentAuthor: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  momentLocation: {
    fontSize: 10,
    color: '#6B7370',
    marginBottom: 6,
  },
  momentCaption: {
    fontSize: 11,
    color: '#6B7370',
    fontStyle: 'italic',
    lineHeight: 15,
  },
  trendingCard: {
    width: 160,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    padding: 12,
    marginRight: 12,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  trendingImageContainer: {
    height: 90,
    backgroundColor: '#F0EDE8',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    position: 'relative',
  },
  trendingImgEmoji: {
    fontSize: 32,
  },
  ratingBadge: {
    position: 'absolute',
    right: 8,
    top: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  ratingText: {
    fontSize: 9,
    color: '#1A1F1E',
    fontWeight: '700',
  },
  trendingName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1F1E',
    marginBottom: 2,
  },
  trendingState: {
    fontSize: 11,
    color: '#6B7370',
    marginBottom: 6,
  },
  trendingVisits: {
    fontSize: 10,
    fontWeight: '600',
    color: '#1A6B5A',
  },
  bottomSpacer: {
    height: 48,
  },
});

export default styles;
