import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    bottom: 18,
    left: 15,
    right: 15,
    height: 72,
    zIndex: 999,
  },
  gradient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    borderRadius: 36,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 12,
  },
  sideGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 100,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 44,
  },
  iconContainer: {
    position: 'relative',
    alignItems: 'center',
  },
  iconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#6FCF97',
    marginTop: 4,
    alignSelf: 'center',
  },
  centerWrapper: {
    position: 'absolute',
    left: '50%',
    marginLeft: -34, // half of 68
    top: -16,
    zIndex: 10,

  },
  centerButton: {
    width: 64,
    height: 64,
    borderRadius: 34,
    backgroundColor: '#D9784F',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
    shadowColor: '#D9784F',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -8,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FF7A45',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  // Host Bottom Tab Bar styles (non-floating, full-width, white background with labels)
  hostContainer: {
    height: Platform.OS === 'ios' ? 88 : 72,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E8E2D9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 24 : 8,
  },
  hostSideGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    flex: 1,
  },
  hostTabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingTop: 6,
    position: 'relative',
  },
  hostIconContainer: {
    position: 'relative',
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hostTabLabel: {
    fontSize: 10,
    fontWeight: '600',
    marginTop: 4,
  },
  hostDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#1A6B5A',
    marginTop: 2,
  },
  hostCenterWrapper: {
    width: 68,
    height: 68,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -28, // float up
    zIndex: 10,
  },
  hostCenterButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#D4704A',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  hostBadge: {
    position: 'absolute',
    top: -4,
    right: -8,
    minWidth: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#D4704A',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  hostBadgeText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '700',
  },
});

export default styles;
