import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  heroHeader: {
    height: 240,
    backgroundColor: '#FAF8F4',
    justifyContent: 'flex-end',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    overflow: 'hidden',
    position: 'relative',
    borderBottomWidth: 1,
    borderBottomColor: '#E8E2D9',
  },
  heroBgImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.12,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FAF8F4',
    opacity: 0.6,
  },
  topRow: {
    position: 'absolute',
    top: 16,
    left: 24,
    right: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoText: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginLeft: 6,
  },
  bellBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  bellBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#D4704A',
    width: 14,
    height: 14,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bellBadgeText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 'bold',
  },
  avatarSection: {
    alignItems: 'center',
    paddingBottom: 24,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 12,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#D4704A',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: 'bold',
  },
  checkBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#1A6B5A',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FAF8F4',
  },
  profileName: {
    color: '#1A1F1E',
    fontSize: 22,
    fontWeight: '700',
    fontFamily: 'serif',
    marginBottom: 6,
  },
  verifiedPill: {
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  verifiedActive: {
    backgroundColor: '#E6F2EF',
  },
  verifiedPending: {
    backgroundColor: '#F0EDE8',
  },
  verifiedText: {
    color: '#1A6B5A',
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  verifiedTextPending: {
    color: '#6B7370',
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  // Tab Bar
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E8E2D9',
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTabButton: {
    borderBottomColor: '#1A6B5A',
  },
  tabButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7370',
  },
  activeTabButtonText: {
    color: '#1A6B5A',
  },
  // Content
  scrollContent: {
    paddingBottom: 120,
  },
  tabContent: {
    padding: 24,
  },
  sectionLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  sectionLabel: {
    color: '#1A1F1E',
    fontSize: 12,
    fontFamily: 'monospace',
    letterSpacing: 1.5,
    fontWeight: '700',
  },
  // Reels Section
  reelsContainer: {
    marginBottom: 24,
  },
  reelsCaption: {
    fontSize: 14,
    color: '#6B7370',
    marginBottom: 12,
  },
  emptyReelsBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderStyle: 'dashed',
    padding: 24,
    alignItems: 'center',
    marginBottom: 24,
  },
  emptyReelsText: {
    fontSize: 14,
    color: '#6B7370',
    marginTop: 8,
    marginBottom: 16,
    textAlign: 'center',
  },
  connectInstaBtn: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  connectInstaText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  storyBox: {
    width: 120,
    height: 160,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#E8E2D9',
    marginRight: 12,
    position: 'relative',
  },
  storyImage: {
    width: '100%',
    height: '100%',
  },
  storyOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  storyPlayBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(26,107,90,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIcon: {
    marginLeft: 2,
  },
  storyTitle: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    right: 8,
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  // Payout Earnings Card
  earningsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    padding: 20,
    marginBottom: 24,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  earningsCol: {
    flex: 1,
    alignItems: 'center',
  },
  earningsVal: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
  },
  earningsLbl: {
    fontSize: 10,
    color: '#6B7370',
    marginTop: 4,
    fontFamily: 'monospace',
  },
  earningsDivider: {
    width: 1,
    height: 32,
    backgroundColor: '#E8E2D9',
  },
  // Host Bio Card
  bioCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    padding: 20,
    marginBottom: 24,
    position: 'relative',
    overflow: 'hidden',
  },
  bioText: {
    fontSize: 14,
    color: '#6B7370',
    lineHeight: 22,
    paddingRight: 40,
  },
  bioLeafIcon: {
    position: 'absolute',
    right: 16,
    bottom: 12,
  },
  // CTA Complete Profile
  ctaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E6F2EF', // Match light green background tint
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(26,107,90,0.15)',
    marginBottom: 24,
  },
  ctaIcon: {
    marginRight: 12,
  },
  ctaMeta: {
    flex: 1,
    marginRight: 8,
  },
  ctaTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A6B5A',
    marginBottom: 2,
  },
  ctaSubtitle: {
    fontSize: 12,
    color: '#6B7370',
    lineHeight: 16,
  },
  ctaButton: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  ctaButtonText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  // Properties List
  propertyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    overflow: 'hidden',
    paddingBottom: 16,
    marginBottom: 20,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  propertyCardImage: {
    width: '100%',
    height: 160,
  },
  propertyCardImagePlaceholder: {
    width: '100%',
    height: 160,
    backgroundColor: '#FAF8F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyCardName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1F1E',
    paddingTop: 12,
    paddingHorizontal: 16,
    fontFamily: 'serif',
  },
  propertyCardLocation: {
    fontSize: 13,
    color: '#6B7370',
    paddingHorizontal: 16,
    marginTop: 2,
  },
  propertyCardPrice: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A6B5A',
    paddingHorizontal: 16,
    marginTop: 6,
  },
  statusBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusActive: {
    backgroundColor: '#E6F2EF',
  },
  statusReview: {
    backgroundColor: '#FDF0EA',
  },
  statusDraft: {
    backgroundColor: '#F0EDE8',
  },
  statusBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    fontFamily: 'monospace',
  },
  statusActiveText: {
    color: '#1A6B5A',
  },
  statusReviewText: {
    color: '#D4704A',
  },
  statusDraftText: {
    color: '#6B7370',
  },
  emptyProperties: {
    alignItems: 'center',
    padding: 32,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1F1E',
    marginTop: 12,
  },
  emptySubText: {
    fontSize: 13,
    color: '#6B7370',
    marginTop: 4,
    textAlign: 'center',
  },
  // Reviews List
  emptyReviewsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyReviewsText: {
    fontSize: 14,
    color: '#6B7370',
    marginTop: 8,
  },
  // Settings List
  settingsList: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 56,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E2D9',
  },
  settingsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  signOutLabel: {
    fontSize: 15,
    color: '#D4704A',
    fontWeight: '700',
  },
  // Complete Profile CTA icon circle
  ctaIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FAF8F4',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  // Mockup large reels card
  storyBoxLargeContainer: {
    marginBottom: 24,
  },
  storyBoxLarge: {
    width: '100%',
    height: 200,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#E8E2D9',
    position: 'relative',
  },
  storyImageLarge: {
    width: '100%',
    height: '100%',
  },
  storyOverlayLarge: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  storyPlayBtnLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  storyTitleLarge: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'serif',
  },
});
