import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 8 : 16,
    paddingBottom: 12,
    backgroundColor: '#0F1714',
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E2B25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#FAF8F4',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 80,
  },
  connectCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    margin: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  instagramIcon: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: '#833AB4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  connectTitle: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: '#1A1F1E',
    marginBottom: 8,
    textAlign: 'center',
  },
  connectSubtitle: {
    fontSize: 14,
    color: '#6B7370',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  benefitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  benefitText: {
    fontSize: 13,
    color: '#1A1F1E',
    fontWeight: '500',
  },
  connectButton: {
    backgroundColor: '#833AB4',
    borderRadius: 100,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginTop: 8,
  },
  connectButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  connectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    marginBottom: 16,
  },
  connectedUsername: {
    fontSize: 14,
    color: '#1A1F1E',
    fontWeight: '600',
    marginBottom: 16,
  },
  connectedBadgeText: {
    fontSize: 12,
    color: '#1A6B5A',
    fontWeight: '700',
  },
  fetchButton: {
    backgroundColor: '#E6F2EF',
    borderColor: '#1A6B5A',
    borderWidth: 1,
    borderRadius: 100,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 12,
  },
  fetchButtonText: {
    color: '#1A6B5A',
    fontSize: 14,
    fontWeight: '700',
  },
  disconnectButton: {
    paddingVertical: 8,
    marginTop: 8,
  },
  disconnectButtonText: {
    color: '#D4704A',
    fontSize: 14,
    fontWeight: '600',
  },
  reelsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    padding: 16,
  },
  reelCell: {
    backgroundColor: '#1A2B25',
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  reelCellSelected: {
    borderWidth: 2,
    borderColor: '#1A6B5A',
  },
  reelThumbnail: {
    width: '100%',
    height: '100%',
  },
  playIcon: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -12 }, { translateY: -12 }],
  },
  selectedBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#1A6B5A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginVertical: 16,
    gap: 12,
  },
  orLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E8E2D9',
  },
  orText: {
    fontSize: 12,
    color: '#6B7370',
    fontWeight: '600',
  },
  manualUploadBtn: {
    borderWidth: 1.5,
    borderColor: '#1A6B5A',
    borderRadius: 100,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
  },
  manualUploadBtnText: {
    color: '#1A6B5A',
    fontSize: 14,
    fontWeight: '700',
  },
  saveButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 16,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  gridHeader: {
    fontSize: 10,
    color: '#6B7370',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: 1.5,
    marginHorizontal: 16,
    marginTop: 16,
    fontWeight: '700',
  },
});
