import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714', // Immersive dark header background area
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF8F4', // Page content background
  },
  headerWrapper: {
    backgroundColor: '#021412',
    height: 110, // Strict fixed height to establish the header/hero sizing hierarchy
    position: 'relative',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
  },
  headerAbsoluteImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.35,
    overflow: 'hidden',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 52 : 36, // Immersive status area offset
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'serif',
    letterSpacing: 0.5,
  },
  headerRightIcons: {
    flexDirection: 'row',
    gap: 12,
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingBottom: 120, // Safe buffer for tab bar overlap
  },
  // Profile Summary Row
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 20,
    marginTop: -5, // Overlaps the curved bottom of the hero header by ~30-40px
  },
  avatarContainer: {
    position: 'relative',
    marginTop: -16, // Pulls only the avatar up further for proper Airbnb overlap look
  },
  avatarCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#1A6B5A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#1A6B5A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  avatarText: {
    fontSize: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'serif',
  },
  editButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  profileInfo: {
    flex: 1,
    paddingTop: 16, // Pushes user details below the header boundary for high contrast readability
  },
  profileName: {
    fontSize: 24,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 4,
  },
  memberChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#E6F2EF',
    borderWidth: 1,
    borderColor: '#D4E8E3',
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 4,
    marginBottom: 4,
  },
  memberChipText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 9,
    fontWeight: '800',
    color: '#1A6B5A',
    letterSpacing: 0.5,
  },
  joinedText: {
    fontSize: 11,
    color: '#6B7370',
    fontWeight: '500',
  },
  // Stats Card
  statsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 18,
    marginHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: 24,
  },
  statColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  statHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1F1E',
    fontFamily: 'serif',
  },
  statLabel: {
    fontSize: 11,
    color: '#6B7370',
    fontWeight: '600',
  },
  statDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#E8E2D9',
  },
  // Become a Host / Switch to Host Mode Card
  hostCard: {
    backgroundColor: '#0F1714',
    borderRadius: 28,
    padding: 20,
    marginHorizontal: 20,
    marginBottom: 24,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  hostCardImageBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.25, // Increased opacity for luxury villa image presence
  },
  hostCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    zIndex: 10,
  },
  hostCardTag: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 9,
    fontWeight: '800',
    color: '#84C9BA',
    letterSpacing: 1,
  },
  hostCardTitle: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#FFFFFF',
    marginBottom: 8,
    zIndex: 10,
  },
  hostCardDesc: {
    fontSize: 13,
    color: '#C6D2CF',
    fontWeight: '500',
    lineHeight: 18,
    marginBottom: 16,
    zIndex: 10,
  },
  hostCardCTA: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  hostCardCTAText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // Profile Tabs
  tabsContainer: {
    flexDirection: 'row',
    borderBottomWidth: 1.5,
    borderBottomColor: '#E8E2D9',
    marginBottom: 24,
    marginHorizontal: 20,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 2.5,
    borderBottomColor: 'transparent',
  },
  activeTabButton: {
    borderBottomColor: '#1A6B5A',
  },
  tabButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6B7370',
  },
  activeTabButtonText: {
    color: '#1A6B5A',
  },
  tabContent: {
    paddingHorizontal: 20,
  },
  // Trip Cards Styling
  tripCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    borderRadius: 20,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  tripImageContainer: {
    height: 180,
    position: 'relative',
    backgroundColor: '#1E2B25',
  },
  tripImage: {
    width: '100%',
    height: '100%',
  },
  tripStatusBadge: {
    position: 'absolute',
    top: 14,
    left: 14,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  tripStatusText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  tripOptionsBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tripInfo: {
    padding: 18,
  },
  tripTitle: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 6,
  },
  tripDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  tripDetailsText: {
    fontSize: 12,
    color: '#6B7370',
    fontWeight: '600',
  },
  tripVibeChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 16,
  },
  tripVibeChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  tripVibeText: {
    color: '#1A6B5A',
    fontSize: 10,
    fontWeight: '700',
  },
  tripActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
    paddingTop: 12,
  },
  tripCTA: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  tripCTAText: {
    color: '#1A6B5A',
    fontSize: 13,
    fontWeight: '700',
  },
  // Saved Tab Styling
  emptySavedContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptySavedTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1F1E',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySavedSubtitle: {
    fontSize: 14,
    color: '#6B7370',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  exploreButton: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    paddingVertical: 12,
    paddingHorizontal: 32,
    shadowColor: '#1A6B5A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  exploreButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  // Saved properties cards
  card: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    borderRadius: 20,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  photoArea: {
    height: 200,
    backgroundColor: '#1E2B25',
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: 200,
  },
  placeholderContainer: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1E2B25',
  },
  scoreBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#1A6B5A',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  scoreValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  scoreText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
    marginTop: 1,
  },
  contentArea: {
    padding: 16,
  },
  row1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  propertyName: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    flex: 1,
    marginRight: 8,
  },
  propertyPrice: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A6B5A',
  },
  row2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  locationText: {
    fontSize: 13,
    color: '#6B7370',
    marginLeft: 4,
  },
  row3: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 16,
  },
  amenityChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  amenityChipText: {
    color: '#1A6B5A',
    fontSize: 11,
    fontWeight: '700',
  },
  row4: {
    marginBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
    paddingTop: 12,
  },
  breakdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  breakdownLabel: {
    fontSize: 11,
    color: '#6B7370',
    fontWeight: '500',
  },
  breakdownBarContainer: {
    width: 80,
    height: 4,
    backgroundColor: '#E8E2D9',
    borderRadius: 2,
    overflow: 'hidden',
  },
  breakdownBar: {
    height: '100%',
    backgroundColor: '#1A6B5A',
    borderRadius: 2,
  },
  row5: {
    flexDirection: 'row',
    gap: 8,
  },
  viewButton: {
    flex: 1,
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  saveButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 100,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#1A1F1E',
    fontSize: 13,
    fontWeight: '700',
  },
  // How it works timeline
  howTitle: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 20,
    textAlign: 'center',
  },
  howStepsContainer: {
    paddingHorizontal: 8,
  },
  howStepRow: {
    flexDirection: 'row',
    marginBottom: 24,
    alignItems: 'flex-start',
  },
  howStepIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#E6F2EF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  howStepTextContainer: {
    flex: 1,
  },
  howStepTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1F1E',
    marginBottom: 4,
  },
  howStepSubtitle: {
    fontSize: 12,
    color: '#6B7370',
    lineHeight: 16,
  },
  // Settings Tab list
  settingsList: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    overflow: 'hidden',
  },
  settingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EDE8',
  },
  settingsItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsItemIcon: {
    marginRight: 12,
  },
  settingsItemLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  signOutLabel: {
    color: '#D4704A',
  },
  chevron: {
    fontSize: 14,
    color: '#6B7370',
  },
});

export default styles;
