import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  topBar: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F1714',
    paddingHorizontal: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  topBarSpacer: {
    width: 40,
  },
  heroSection: {
    padding: 24,
    backgroundColor: '#0F1714',
  },
  heroTitle: {
    fontFamily: 'serif',
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 8,
  },
  heroSubtitle: {
    color: '#84C9BA',
    fontSize: 14,
    marginBottom: 12,
  },
  moodsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  moodChip: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  moodChipText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  scrollContent: {
    paddingBottom: 32,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    overflow: 'hidden',
  },
  photoArea: {
    height: 200,
    backgroundColor: '#1E2B25',
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: 200,
  },
  placeholderContainer: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1A2B25',
  },
  scoreBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#1A6B5A',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  scoreValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  scoreText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
    marginTop: 1,
  },
  contentArea: {
    padding: 16,
  },
  row1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  propertyName: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    flex: 1,
    marginRight: 8,
  },
  propertyPrice: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A6B5A',
  },
  row2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  locationText: {
    fontSize: 13,
    color: '#6B7370',
    marginLeft: 4,
  },
  row3: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 16,
  },
  amenityChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  amenityChipText: {
    color: '#1A6B5A',
    fontSize: 11,
    fontWeight: '600',
  },
  row4: {
    marginBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
    paddingTop: 12,
  },
  breakdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  breakdownLabel: {
    fontSize: 11,
    color: '#6B7370',
    fontWeight: '500',
  },
  breakdownBarContainer: {
    width: 80,
    height: 4,
    backgroundColor: '#E8E2D9',
    borderRadius: 2,
    overflow: 'hidden',
  },
  breakdownBar: {
    height: '100%',
    backgroundColor: '#1A6B5A',
    borderRadius: 2,
  },
  row5: {
    gap: 8,
  },
  viewButton: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  saveButton: {
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 100,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#1A1F1E',
    fontSize: 14,
    fontWeight: '700',
  },
  conciergeLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#0F1714',
  },
  loaderSpinner: {
    marginBottom: 24,
  },
  loadingTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'serif',
    marginBottom: 8,
    textAlign: 'center',
  },
  loadingSubtitle: {
    fontSize: 14,
    color: '#84C9BA',
    marginBottom: 40,
    textAlign: 'center',
  },
  checklistWrapper: {
    width: '100%',
    backgroundColor: '#1E2B25',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(132, 201, 186, 0.1)',
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  checkIcon: {
    width: 24,
    marginRight: 12,
  },
  checklistText: {
    fontSize: 14,
    color: '#6B7370',
    fontWeight: '500',
  },
  checklistTextCompleted: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  checklistTextActive: {
    color: '#D4704A',
    fontWeight: '700',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#0F1714',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#FFFFFF',
    marginTop: 16,
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 14,
    color: '#6B7370',
    marginBottom: 24,
    textAlign: 'center',
  },
  backToPlanBtn: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 48,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backToPlanText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
});
