import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F8F7F4',
  },
  container: {
    flex: 1,
    backgroundColor: '#F8F7F4',
  },
  topBar: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8F7F4',
    paddingHorizontal: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBarTitle: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    textAlign: 'center',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  filterButtonText: {
    fontSize: 13,
    color: '#1A1F1E',
    fontWeight: '600',
  },
  heroSection: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
  },
  heroTitle: {
    fontFamily: 'serif',
    color: '#1A1F1E',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 36,
  },
  destinationText: {
    fontFamily: 'serif',
    fontStyle: 'italic',
    color: '#1A6B5A',
  },
  heroSubtitle: {
    color: '#6B7370',
    fontSize: 14,
    marginTop: 6,
    marginBottom: 12,
  },
  moodsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  moodChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  moodChipText: {
    color: '#1A6B5A',
    fontSize: 12,
    fontWeight: '600',
  },
  scrollContent: {
    paddingBottom: 120, // offset for floating bottom nav
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  photoArea: {
    height: 220,
    position: 'relative',
    backgroundColor: '#F0EDE8',
  },
  cardImage: {
    width: '100%',
    height: 220,
  },
  placeholderContainer: {
    width: '100%',
    height: 220,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F0EDE8',
  },
  badgeContainer: {
    position: 'absolute',
    top: 16,
    left: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  scoreRing: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#FFFFFF',
    borderWidth: 4,
    borderColor: '#1A6B5A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  scoreValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
  },
  scoreText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#6B7370',
    letterSpacing: 0.5,
    marginTop: 1,
  },
  contentArea: {
    padding: 20,
  },
  propertyInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  propertyName: {
    fontSize: 20,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    flex: 1,
    marginRight: 8,
  },
  priceCol: {
    alignItems: 'flex-end',
  },
  propertyPrice: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A6B5A',
    fontFamily: 'serif',
  },
  nightsText: {
    fontSize: 11,
    color: '#6B7370',
    marginTop: 2,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  locationText: {
    fontSize: 13,
    color: '#6B7370',
    marginLeft: 4,
  },
  amenitiesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  amenityChip: {
    backgroundColor: '#F0EDE8',
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  amenityChipText: {
    color: '#1A1F1E',
    fontSize: 11,
    fontWeight: '600',
  },
  matchReasonsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 16,
  },
  matchReasonChip: {
    backgroundColor: '#FDF2E9',
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(212, 112, 79, 0.15)',
  },
  matchReasonChipText: {
    color: '#D4704A',
    fontSize: 11,
    fontWeight: '700',
  },
  breakdownSection: {
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
    paddingTop: 16,
    marginBottom: 18,
  },
  breakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  breakdownLabelCol: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 100,
    gap: 8,
  },
  breakdownLabelText: {
    fontSize: 13,
    color: '#1A1F1E',
    fontWeight: '500',
  },
  progressBarContainer: {
    flex: 1,
    height: 6,
    backgroundColor: '#E8E2D9',
    borderRadius: 3,
    overflow: 'hidden',
    marginHorizontal: 12,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#1A6B5A',
    borderRadius: 3,
  },
  breakdownValueText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A1F1E',
    width: 32,
    textAlign: 'right',
  },
  cardActionsRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  viewButton: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    height: 52,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  saveCircleButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#F8F7F4',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginTop: 16,
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 14,
    color: '#6B7370',
    marginBottom: 24,
    textAlign: 'center',
  },
  backToPlanBtn: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 48,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backToPlanText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
});
