import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  topBar: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F1714',
    paddingHorizontal: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  topBarSpacer: {
    width: 40,
  },
  heroSection: {
    padding: 24,
    backgroundColor: '#0F1714',
  },
  heroTitle: {
    fontFamily: 'serif',
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 8,
  },
  heroSubtitle: {
    color: '#84C9BA',
    fontSize: 14,
    marginBottom: 12,
  },
  moodsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  moodChip: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  moodChipText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  scrollContent: {
    paddingBottom: 32,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    overflow: 'hidden',
  },
  photoArea: {
    height: 200,
    backgroundColor: '#1E2B25',
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: 200,
  },
  placeholderContainer: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1A2B25',
  },
  scoreBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#1A6B5A',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  scoreValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  scoreText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
    marginTop: 1,
  },
  contentArea: {
    padding: 16,
  },
  row1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  propertyName: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    flex: 1,
    marginRight: 8,
  },
  propertyPrice: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A6B5A',
  },
  row2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  locationText: {
    fontSize: 13,
    color: '#6B7370',
    marginLeft: 4,
  },
  row3: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 16,
  },
  amenityChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  amenityChipText: {
    color: '#1A6B5A',
    fontSize: 11,
    fontWeight: '600',
  },
  row4: {
    marginBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
    paddingTop: 12,
  },
  breakdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  breakdownLabel: {
    fontSize: 11,
    color: '#6B7370',
    fontWeight: '500',
  },
  breakdownBarContainer: {
    width: 80,
    height: 4,
    backgroundColor: '#E8E2D9',
    borderRadius: 2,
    overflow: 'hidden',
  },
  breakdownBar: {
    height: '100%',
    backgroundColor: '#1A6B5A',
    borderRadius: 2,
  },
  row5: {
    gap: 8,
  },
  viewButton: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  saveButton: {
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 100,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#1A1F1E',
    fontSize: 14,
    fontWeight: '700',
  },
  conciergeLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#F8F7F3',
    paddingTop: 30,
  },
  heroArea: {
    width: 220,
    height: 220,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
    position: 'relative',
  },
  glowRing: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: 'rgba(27, 122, 105, 0.08)',
    backgroundColor: 'rgba(27, 122, 105, 0.02)',
  },
  orbitRing: {
    position: 'absolute',
    width: 188,
    height: 188,
    borderRadius: 94,
    borderWidth: 1.5,
    borderColor: 'rgba(27, 122, 105, 0.15)',
  },
  orbitContainer: {
    position: 'absolute',
    width: 188,
    height: 188,
  },
  orbitDot: {
    position: 'absolute',
    top: -4,
    left: 90,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#1B7A69',
    shadowColor: '#1B7A69',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  centerCanvas: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#E6F2EF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#1B7A69',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 4,
  },
  decorCloud: {
    position: 'absolute',
    top: 27,
    right: 18,
    opacity: 0.4,
  },
  decorPalm: {
    position: 'absolute',
    bottom: -4,
    left: 14,
    opacity: 0.7,
  },
  decorPalmRight: {
    position: 'absolute',
    bottom: -8,
    right: 14,
    opacity: 0.4,
    transform: [{ scaleX: -1 }],
  },
  decorSuitcase: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    zIndex: 5,
  },
  suitcaseHandle: {
    width: 24,
    height: 14,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderWidth: 2.5,
    borderColor: '#1B7A69',
    borderBottomWidth: 0,
    marginBottom: -2,
  },
  suitcaseBody: {
    width: 54,
    height: 72,
    borderRadius: 12,
    backgroundColor: '#98D5C8',
    borderWidth: 2.5,
    borderColor: '#1B7A69',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#1B7A69',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  suitcaseStrapLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    width: 2.5,
    backgroundColor: '#1B7A69',
    opacity: 0.3,
  },
  suitcaseStrapRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    width: 2.5,
    backgroundColor: '#1B7A69',
    opacity: 0.3,
  },
  suitcaseBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#1B7A69',
  },
  suitcaseWheelsRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 1,
  },
  suitcaseWheel: {
    width: 6,
    height: 5,
    borderRadius: 2,
    backgroundColor: '#1B7A69',
  },
  floatingParticle: {
    position: 'absolute',
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#1B7A69',
    opacity: 0.25,
  },
  loadingTitle: {
    fontFamily: 'serif',
    fontSize: 26,
    fontWeight: '800',
    color: '#1A1F1E',
    marginBottom: 8,
    textAlign: 'center',
  },
  loadingSubtitle: {
    fontSize: 14,
    color: '#1B7A69',
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 24,
  },
  checklistWrapper: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E6E8E5',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.02,
    shadowRadius: 10,
    elevation: 3,
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    position: 'relative',
    paddingBottom: 22,
  },
  checklistItemLast: {
    paddingBottom: 0,
  },
  verticalLine: {
    position: 'absolute',
    left: 12,
    top: 24,
    bottom: -6,
    width: 1.5,
    backgroundColor: '#E6E8E5',
    zIndex: 1,
  },
  verticalLineActive: {
    backgroundColor: '#1B7A69',
  },
  checkIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F8F7F3',
    borderWidth: 1.5,
    borderColor: '#E6E8E5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    zIndex: 2,
  },
  checkIconCompleted: {
    backgroundColor: '#E6F2EF',
    borderColor: '#1B7A69',
  },
  checkIconActive: {
    backgroundColor: '#FDF2E9',
    borderColor: '#D67A4A',
  },
  checklistText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8C9591',
    lineHeight: 20,
  },
  checklistTextCompleted: {
    color: '#1A1F1E',
    fontWeight: '700',
  },
  checklistTextActive: {
    color: '#D67A4A',
    fontWeight: '700',
  },
  helperText: {
    fontSize: 11,
    color: '#8C9591',
    fontWeight: '500',
    marginTop: 2,
  },
  helperTextCompleted: {
    color: '#6B7370',
  },
  helperTextActive: {
    color: '#D67A4A',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#0F1714',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#FFFFFF',
    marginTop: 16,
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 14,
    color: '#6B7370',
    marginBottom: 24,
    textAlign: 'center',
  },
  backToPlanBtn: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 48,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backToPlanText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
});
