import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  headerContainer: {
    height: 250,
    backgroundColor: '#0F1714',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    overflow: 'hidden',
  },
  headerBgImage: {
    width: '100%',
    height: '100%',
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  headerContent: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 16,
    paddingBottom: 15,
    paddingHorizontal: 24,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  welcomeText: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#84C9BA',
  },
  logoTitle: {
    fontSize: 22,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#FFFFFF',
    marginTop: 2,
  },
  bellButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bellBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#D4704A',
    width: 14,
    height: 14,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bellBadgeText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 'bold',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 5,
    marginTop: 5,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#1E2F28', // Dark forest green background
    borderWidth: 1,
    borderColor: '#2D5A42',
    borderRadius: 16,
    padding: 12,
    minHeight: 110,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  statValue: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    fontFamily: 'serif',
    marginTop: 6,
  },
  statLabel: {
    color: '#84C9BA',
    fontSize: 9,
    fontFamily: 'monospace',
    letterSpacing: 0.5,
    marginTop: 4,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  // Section Headers
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#1A1F1E',
    letterSpacing: 1.5,
  },
  sectionAction: {
    fontSize: 13,
    fontWeight: '700',
    color: '#D4704A',
  },
  // Properties Scroll
  propertiesScroll: {
    paddingLeft: 24,
    paddingRight: 12,
  },
  propertyCard: {
    width: 180,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    marginRight: 12,
    overflow: 'hidden',
    paddingBottom: 12,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  propertyCardImage: {
    width: '100%',
    height: 110,
  },
  propertyCardImagePlaceholder: {
    width: '100%',
    height: 110,
    backgroundColor: '#FAF8F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyCardName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1F1E',
    fontFamily: 'serif',
    marginTop: 8,
    paddingHorizontal: 12,
  },
  propertyCardLocation: {
    fontSize: 12,
    color: '#6B7370',
    paddingHorizontal: 12,
    marginTop: 2,
  },
  propertyCardPrice: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A6B5A',
    paddingHorizontal: 12,
    marginTop: 6,
  },
  statusBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    borderRadius: 100,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  statusActive: {
    backgroundColor: '#E6F2EF',
  },
  statusReview: {
    backgroundColor: '#FDF0EA',
  },
  statusDraft: {
    backgroundColor: '#F0EDE8',
  },
  statusBadgeText: {
    fontSize: 8,
    fontWeight: '800',
    fontFamily: 'monospace',
  },
  statusActiveText: {
    color: '#1A6B5A',
  },
  statusReviewText: {
    color: '#D4704A',
  },
  statusDraftText: {
    color: '#6B7370',
  },
  emptyPropertiesBox: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#E8E2D9',
    borderRadius: 22,
    marginHorizontal: 24,
    height: 170,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  emptyPropertiesIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#E6F2EF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  emptyPropertiesText: {
    fontSize: 14,
    color: '#1A1F1E',
    fontWeight: '700',
    marginTop: 4,
  },
  emptyPropertiesSub: {
    fontSize: 12,
    color: '#6B7370',
    marginTop: 2,
  },
  // Booking List
  bookingsList: {
    paddingHorizontal: 24,
  },
  bookingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    padding: 12,
    marginBottom: 10,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  bookingDetails: {
    flex: 1,
  },
  bookingName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  bookingSub: {
    fontSize: 12,
    color: '#6B7370',
    marginTop: 2,
  },
  bookingRight: {
    alignItems: 'flex-end',
  },
  bookingAmount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1F1E',
    marginBottom: 4,
  },
  rowStatusChip: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 100,
  },
  rowStatusText: {
    fontSize: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  emptyBookingsBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
  },
  emptyBookingsText: {
    fontSize: 13,
    color: '#6B7370',
    marginTop: 6,
  },
});
