import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F8F7F3',
  },
  container: {
    flex: 1,
    backgroundColor: '#F8F7F3',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  // Hero Header
  heroHeader: {
    height: 160,
    position: 'relative',
    overflow: 'hidden',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    backgroundColor: '#0B5D4B',
  },
  heroBgImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.75,
  },
  gradientOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  logoWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Platform.OS === 'ios' ? 60 : 40,
    flexDirection: 'row',
    gap: 6,
  },
  logoText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    letterSpacing: 0.5,
  },
  // Celebration Success Circle Overlay
  celebrationWrapper: {
    alignItems: 'center',
    marginTop: -55,
    zIndex: 10,
  },
  celebrationCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#EEF8F4',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0B5D4B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    position: 'relative',
  },
  badgeCircle: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#0B5D4B',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2.5,
    borderColor: '#F8F7F3',
  },
  // Title text block
  titleSection: {
    alignItems: 'center',
    paddingHorizontal: 32,
    marginTop: 24,
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    textAlign: 'center',
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 15,
    color: '#6B7370',
    textAlign: 'center',
    lineHeight: 22,
  },
  boldTime: {
    color: '#0B5D4B',
    fontWeight: '700',
  },
  // Combined Review Timeline & Preview Card
  timelineCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginHorizontal: 24,
    marginBottom: 20,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#E8E5DD',
  },
  // Timeline Horizontal Rows
  stepsWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
    position: 'relative',
    paddingHorizontal: 4,
  },
  stepLine: {
    position: 'absolute',
    top: 18,
    height: 2.5,
    backgroundColor: '#E8E5DD',
    zIndex: 1,
  },
  stepLine1: {
    left: '16.6%',
    right: '50%',
  },
  stepLine1Active: {
    backgroundColor: '#E67E52',
  },
  stepLine2: {
    left: '50%',
    right: '16.6%',
  },
  stepItem: {
    flex: 1,
    alignItems: 'center',
    zIndex: 2,
  },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E8E5DD',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleSubmitted: {
    backgroundColor: '#E67E52',
    borderColor: '#E67E52',
  },
  stepCircleInReview: {
    borderColor: '#E67E52',
    backgroundColor: '#FFFFFF',
  },
  stepCircleActive: {
    borderColor: '#E8E5DD',
    backgroundColor: '#FFFFFF',
  },
  stepLabel: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
    color: '#8E9A96',
    textAlign: 'center',
  },
  stepLabelSubmitted: {
    color: '#E67E52',
  },
  stepLabelInReview: {
    color: '#1A1F1E',
  },
  stepLabelActive: {
    color: '#8E9A96',
  },
  stepSub: {
    fontSize: 10,
    color: '#8E9A96',
    marginTop: 2,
    textAlign: 'center',
  },
  // Divider
  divider: {
    height: 1,
    backgroundColor: '#E8E5DD',
    marginVertical: 20,
  },
  // Property Card inside White Card
  previewWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  previewImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginRight: 16,
    backgroundColor: '#EEF8F4',
  },
  previewContent: {
    flex: 1,
  },
  previewName: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 6,
  },
  previewDetailsText: {
    fontSize: 12,
    color: '#6B7370',
    marginBottom: 8,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FDF0EA',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  reviewBadgeText: {
    color: '#E67E52',
    fontSize: 11,
    fontWeight: '700',
    marginLeft: 4,
  },
  // What Happens Next
  infoCard: {
    flexDirection: 'row',
    backgroundColor: '#EEF8F4',
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 24,
    marginBottom: 32,
    alignItems: 'center',
  },
  infoIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(11,93,75,0.06)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  infoContent: {
    flex: 1,
  },
  infoTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0B5D4B',
    marginBottom: 4,
  },
  infoBody: {
    fontSize: 13,
    color: '#6B7370',
    lineHeight: 18,
  },
  // CTAs
  primaryBtn: {
    flexDirection: 'row',
    height: 56,
    borderRadius: 18,
    backgroundColor: '#E67E52',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 24,
    marginBottom: 16,
    shadowColor: '#E67E52',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  primaryBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  secondaryBtn: {
    flexDirection: 'row',
    height: 56,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#0B5D4B',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 24,
    marginBottom: 24,
  },
  secondaryBtnText: {
    color: '#0B5D4B',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
});
