import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  topBrand: {
    color: '#84C9BA',
    fontSize: 16,
    fontFamily: 'serif',
    fontWeight: '700',
    marginBottom: 40,
  },
  celebrationBox: {
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    fontFamily: 'serif',
    textAlign: 'center',
    marginBottom: 12,
  },
  subtitle: {
    color: '#84C9BA',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 40,
    paddingHorizontal: 16,
  },
  // Horizontal Progress Steps
  stepsWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 40,
  },
  stepContainer: {
    alignItems: 'center',
    width: 70,
  },
  stepCircleFilled: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#D4704A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: '#0F1714',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleInactive: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#6B7370',
    backgroundColor: '#0F1714',
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: '#6B7370',
    marginTop: -16,
  },
  stepLineActive: {
    backgroundColor: '#D4704A',
  },
  stepLabel: {
    color: '#6B7370',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: '#FFFFFF',
  },
  stepLabelCompleted: {
    color: '#D4704A',
  },
  // Property Preview Card
  previewCard: {
    backgroundColor: '#1E2B25',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 40,
    borderWidth: 1,
    borderColor: '#1E2B25',
  },
  previewImgPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: '#0F1714',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  previewDetails: {
    flex: 1,
  },
  previewName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'serif',
    marginBottom: 6,
  },
  reviewChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#D4704A',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  reviewChipText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 'bold',
  },
  // Bottom button
  button: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 52,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  editBtnText: {
    color: '#6B7370',
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 8,
  },
});
