import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  heroHeader: {
    height: 250,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    overflow: 'hidden',
    position: 'relative',
  },
  heroImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 44 : 24,
    paddingHorizontal: 16,
    height: 80,
    justifyContent: 'space-between',
    zIndex: 10,
  },
  circleBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroContent: {
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: 10,
    zIndex: 5,
  },
  heroTitle: {
    fontSize: 30,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  heroSubtitle: {
    fontSize: 13,
    color: '#84C9BA',
    marginTop: 6,
    textAlign: 'center',
    fontWeight: '600',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginTop: 24,
    paddingHorizontal: 20,
    zIndex: 5,
  },
  stepItem: {
    alignItems: 'center',
    width: 70,
  },
  stepDotCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 6,
  },
  stepDotCircleActive: {
    borderColor: '#1A6B5A',
    backgroundColor: '#1A6B5A',
  },
  stepDotCircleCompleted: {
    borderColor: '#1A6B5A',
    backgroundColor: '#1A6B5A',
  },
  stepDotNum: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  stepLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.6)',
    marginTop: 6,
    fontWeight: '600',
    textAlign: 'center',
  },
  stepLabelActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  stepLabelCompleted: {
    color: '#84C9BA',
    fontWeight: '600',
  },
  stepperLine: {
    height: 2,
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
    marginHorizontal: -10,
    marginTop: -20,
    zIndex: 1,
  },
  stepperLineCompleted: {
    backgroundColor: '#1A6B5A',
  },
  simpleHeader: {
    height: 200,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    backgroundColor: '#0F1714',
    overflow: 'hidden',
    position: 'relative',
  },
  simpleHeaderContent: {
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: -10,
    zIndex: 5,
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#FAF8F4',
  },
  formContent: {
    padding: 24,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    backgroundColor: '#FAF8F4',
    marginTop: -20,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: '#6B7370',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 14,
    height: 56,
    paddingHorizontal: 16,
  },
  leftIcon: {
    marginRight: 12,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    color: '#1A1F1E',
    padding: 0,
  },
  textInputDisabled: {
    backgroundColor: '#F0EDE8',
    color: '#6B7370',
  },
  continueButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 16,
  },
  uploadBox: {
    height: 160,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    borderStyle: 'dashed',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  uploadBoxFilled: {
    borderStyle: 'solid',
    borderColor: '#1A6B5A',
  },
  uploadImage: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  uploadText: {
    fontSize: 13,
    color: '#6B7370',
    marginTop: 8,
  },
  verifyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E6F2EF',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    gap: 8,
  },
  verifyBadgeText: {
    fontSize: 12,
    color: '#1A6B5A',
    fontWeight: '600',
  },
  selectorContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  selectorOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E2D9',
    borderRadius: 100,
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 6,
  },
  selectorOptionActive: {
    borderColor: '#1A6B5A',
    backgroundColor: '#E6F2EF',
  },
  selectorOptionText: {
    fontSize: 13,
    color: '#6B7370',
    fontWeight: '600',
  },
  selectorOptionTextActive: {
    color: '#1A6B5A',
    fontWeight: '700',
  },
  radioOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#6B7370',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    borderColor: '#1A6B5A',
  },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#1A6B5A',
  },
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    marginBottom: 16,
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FAF8F4',
  },
  reviewLabel: {
    fontSize: 14,
    color: '#6B7370',
  },
  reviewValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  previewRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  previewContainer: {
    flex: 1,
  },
  previewLabel: {
    fontSize: 12,
    color: '#6B7370',
    marginBottom: 6,
  },
  previewThumbnail: {
    width: '100%',
    height: 100,
    borderRadius: 8,
    backgroundColor: '#E8E2D9',
  },
});
