import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const headerHeight = Math.min(screenWidth * 0.65, 320);

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  container: {
    flex: 1,
    backgroundColor: '#0F1714',
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#FAF8F4',
    paddingBottom: 40,
    borderTopLeftRadius: 32, // Airbnb curved edge
    marginTop: -24, // 24px content overlap
    overflow: 'hidden',
  },
  headerBackground: {
    backgroundColor: '#0F1714',
    height: headerHeight,
    position: 'relative',
  },
  topRightImageContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: '70%',
    height: '100%',
    borderBottomLeftRadius: 180, // Organic curved edge
    overflow: 'hidden',
    zIndex: 10,
  },
  headerImage: {
    width: '100%',
    height: '100%',
    opacity: 0.85,
  },
  headerBottomFade: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 48,
    zIndex: 15,
  },
  headerContent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: Platform.OS === 'ios' ? 48 : 36,
    paddingHorizontal: 24,
    zIndex: 20,
  },
  backButtonRow: {
    flexDirection: 'row',
    marginBottom: 24, // Consistent spacing
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepIndicator: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 12,
    color: '#FFFFFF', // Step label to white
    letterSpacing: 1.5,
    fontWeight: '800',
    marginBottom: 20, // Consistent spacing
  },
  progressBarContainer: {
    flexDirection: 'row',
    gap: 6,
    width: '60%',
  },
  progressSegment: {
    flex: 1,
    height: 6, // 6px progress bar
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  progressSegmentFilled: {
    backgroundColor: '#1A6B5A',
    // Subtle Linear.app style shadow glow (not gaming app neon)
    shadowColor: '#1A6B5A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  title: {
    fontFamily: 'serif',
    fontSize: 28,
    fontWeight: '800',
    color: '#1A1F1E',
    marginBottom: 6,
    lineHeight: 38,
    letterSpacing: 0.3,
  },
  subtitle: {
    fontSize: 14,
    color: '#6B7370',
    marginBottom: 24,
    lineHeight: 20,
  },
  budgetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  budgetLabel: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 9,
    fontWeight: '700',
    color: '#6B7370',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  totalForAllChip: {
    backgroundColor: '#E6F2EF',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  totalForAllText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 9,
    fontWeight: '700',
    color: '#1A6B5A',
    letterSpacing: 0.5,
  },
  budgetCard: {
    backgroundColor: '#F0F9F7',
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    alignItems: 'center',
  },
  budgetAmount: {
    fontFamily: 'serif',
    fontSize: 36,
    fontWeight: '800',
    color: '#1A6B5A',
    marginBottom: 8,
  },
  budgetSubtitleText: {
    fontSize: 12,
    color: '#6B7370',
    marginBottom: 20,
  },
  sliderContainer: {
    width: '100%',
  },
  slider: {
    width: '100%',
    height: 40,
  },
  sliderLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  sliderLabel: {
    fontSize: 12,
    color: '#6B7370',
    fontWeight: '700',
  },
  budgetChipsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 32,
    flexWrap: 'wrap',
  },
  budgetChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    backgroundColor: '#FFFFFF',
  },
  budgetChipSelected: {
    backgroundColor: '#1A6B5A',
    borderColor: '#1A6B5A',
    shadowColor: '#1A6B5A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  budgetChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  budgetChipTextSelected: {
    color: '#FFFFFF',
  },
  specificLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  specificLabel: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 9,
    fontWeight: '700',
    color: '#1A6B5A',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  specificInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    borderRadius: 16,
    padding: 16,
    minHeight: 100,
    fontSize: 14,
    color: '#1A1F1E',
    textAlignVertical: 'top',
    lineHeight: 20,
    marginBottom: 24,
  },
  aiInsightCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#EBF3FE',
    borderWidth: 1,
    borderColor: '#D4E8E3',
    borderRadius: 16,
    padding: 16,
    marginBottom: 32,
    gap: 12,
  },
  aiInsightIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#D4E8E3',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  aiInsightContent: {
    flex: 1,
  },
  aiInsightTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 10,
    fontWeight: '800',
    color: '#1A6B5A',
    letterSpacing: 1,
    marginBottom: 4,
  },
  aiInsightDesc: {
    fontSize: 12,
    color: '#6B7370',
    lineHeight: 16,
  },
  matchButton: {
    backgroundColor: '#D4704A',
    borderRadius: 100,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    flexDirection: 'row',
    gap: 8,
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  matchButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  aiNoteContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 12,
    paddingHorizontal: 40,
  },
  aiNote: {
    fontSize: 11,
    color: '#6B7370',
    textAlign: 'center',
    lineHeight: 16,
  },
});

export default styles;
