import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const dayWidth = (screenWidth - 32) / 7; // 16px horizontal padding on each side

export default StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    backgroundColor: '#F8F7F3',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: '92%',
    minHeight: '80%',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 24,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerTitleContainer: {
    flex: 1,
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 22,
    fontWeight: '800',
    color: '#1A1F1E',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#6B7370',
    fontWeight: '500',
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EAE6DF',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 16,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 100, // Safe padding for sticky bottom button
  },
  // Trip Summary Card
  tripSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 8,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  tripSummaryLeft: {
    flex: 1,
  },
  tripSummaryDest: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1F1E',
    marginBottom: 4,
  },
  tripSummaryDates: {
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '800',
    color: '#1B7A69',
    marginBottom: 4,
  },
  tripSummaryMeta: {
    fontSize: 12,
    color: '#6B7370',
    fontWeight: '600',
  },
  tripSummaryRight: {
    alignItems: 'flex-end',
  },
  badge: {
    backgroundColor: '#F0F9F7',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4E8E3',
    marginBottom: 4,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#1B7A69',
  },
  tripSummaryHelper: {
    fontSize: 11,
    color: '#D67A4A',
    fontWeight: '600',
  },
  // Calendar Section
  calendarContainer: {
    marginBottom: 20,
  },
  monthHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  monthTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E6F2EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekLabelsRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  weekLabelCell: {
    width: dayWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekLabel: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 11,
    fontWeight: '700',
    color: '#8C9591',
    letterSpacing: 0.5,
  },
  daysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  dayCell: {
    width: dayWidth,
    height: 64, // Keep enough room for label or dot below
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 4,
    position: 'relative',
  },
  // Range selections background highlights
  rangeHighlightLeft: {
    position: 'absolute',
    left: 0,
    right: '50%',
    top: 6,
    bottom: 22,
    backgroundColor: '#E6F2EF',
  },
  rangeHighlightRight: {
    position: 'absolute',
    left: '50%',
    right: 0,
    top: 6,
    bottom: 22,
    backgroundColor: '#E6F2EF',
  },
  rangeHighlightMiddle: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 6,
    bottom: 22,
    backgroundColor: '#E6F2EF',
  },
  dayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  dayCircleSelected: {
    backgroundColor: '#1B7A69',
  },
  dayText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  dayTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  dayTextDisabled: {
    color: '#D0D3D1',
  },
  dayTextInRange: {
    color: '#1B7A69',
    fontWeight: '700',
  },
  // Pills & Dots
  checkLabelPill: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#E6F2EF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#D4E8E3',
    zIndex: 5,
  },
  checkLabelText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#1B7A69',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#1B7A69',
    position: 'absolute',
    bottom: 10,
    zIndex: 5,
  },
  // Summary Section (Selected Dates card)
  bottomSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#E8E2D9',
    padding: 16,
    marginHorizontal: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  summaryCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  calendarIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#1B7A69',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  checkBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  summaryCardDetails: {
    flex: 1,
  },
  summaryLabel: {
    fontSize: 12,
    color: '#8C9591',
    fontWeight: '600',
    marginBottom: 2,
  },
  summaryDatesText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1B7A69',
    marginBottom: 2,
  },
  summaryHelperText: {
    fontSize: 11,
    color: '#8C9591',
    fontWeight: '500',
  },
  guestsCardRight: {
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: '#E8E2D9',
    paddingLeft: 16,
  },
  guestIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E6F2EF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  guestsCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1B7A69',
  },
  // Legend Row
  legendRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    marginBottom: 24,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#1B7A69',
  },
  legendBar: {
    width: 32,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E6F2EF',
  },
  legendText: {
    fontSize: 11,
    color: '#6B7370',
    fontWeight: '600',
  },
  // AI Travel Insight Card
  insightCard: {
    backgroundColor: '#F0F9F7',
    borderWidth: 1,
    borderColor: '#D4E8E3',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 8,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  insightIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#D4E8E3',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  insightContent: {
    flex: 1,
  },
  insightTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 11,
    fontWeight: '800',
    color: '#1B7A69',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  insightText: {
    fontSize: 13,
    color: '#6B7370',
    lineHeight: 18,
    fontWeight: '500',
  },
  // Sticky Bottom CTA Button Container
  stickyBottomContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#F8F7F3',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    borderTopWidth: 1.5,
    borderColor: '#E8E2D9',
  },
  confirmButton: {
    backgroundColor: '#D67A4A',
    height: 56,
    borderRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#D67A4A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
