import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const scannerSize = 180;

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#021412',
  },
  container: {
    flex: 1,
    backgroundColor: '#F8F7F3',
  },
  headerWrapper: {
    backgroundColor: '#021412',
    height: 100,
    position: 'relative',
  
    overflow: 'hidden',
  },
  headerAbsoluteImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.35,
  
    overflow: 'hidden',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 52 : 36,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'serif',
    letterSpacing: 0.5,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingBottom: 48,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  heroArea: {
    width: scannerSize + 40,
    height: scannerSize + 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
    position: 'relative',
  },
  glowRing: {
    position: 'absolute',
    width: scannerSize + 20,
    height: scannerSize + 20,
    borderRadius: (scannerSize + 20) / 2,
    borderWidth: 1.5,
    borderColor: 'rgba(27, 122, 105, 0.08)',
    backgroundColor: 'rgba(27, 122, 105, 0.02)',
  },
  orbitRing: {
    position: 'absolute',
    width: scannerSize + 8,
    height: scannerSize + 8,
    borderRadius: (scannerSize + 8) / 2,
    borderWidth: 1.5,
    borderColor: 'rgba(27, 122, 105, 0.15)',
  },
  orbitContainer: {
    position: 'absolute',
    width: scannerSize + 8,
    height: scannerSize + 8,
  },
  orbitDot: {
    position: 'absolute',
    top: -4,
    left: (scannerSize + 8) / 2 - 4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#1B7A69',
    shadowColor: '#1B7A69',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  centerCanvas: {
    width: scannerSize,
    height: scannerSize,
    borderRadius: scannerSize / 2,
    backgroundColor: '#E6F2EF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#1B7A69',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 4,
  },
  decorCloud: {
    position: 'absolute',
    top: scannerSize * 0.15,
    right: scannerSize * 0.1,
    opacity: 0.4,
  },
  decorPalm: {
    position: 'absolute',
    bottom: -4,
    left: scannerSize * 0.08,
    opacity: 0.7,
  },
  decorPalmRight: {
    position: 'absolute',
    bottom: -8,
    right: scannerSize * 0.08,
    opacity: 0.4,
    transform: [{ scaleX: -1 }],
  },
  decorSuitcase: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    zIndex: 5,
  },
  suitcaseHandle: {
    width: 24,
    height: 14,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderWidth: 2.5,
    borderColor: '#1B7A69',
    borderBottomWidth: 0,
    marginBottom: -2,
  },
  suitcaseBody: {
    width: 54,
    height: 72,
    borderRadius: 12,
    backgroundColor: '#98D5C8',
    borderWidth: 2.5,
    borderColor: '#1B7A69',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#1B7A69',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  suitcaseStrapLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    width: 2.5,
    backgroundColor: '#1B7A69',
    opacity: 0.3,
  },
  suitcaseStrapRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    width: 2.5,
    backgroundColor: '#1B7A69',
    opacity: 0.3,
  },
  suitcaseBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#1B7A69',
  },
  suitcaseWheelsRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 1,
  },
  suitcaseWheel: {
    width: 6,
    height: 5,
    borderRadius: 2,
    backgroundColor: '#1B7A69',
  },
  floatingParticle: {
    position: 'absolute',
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#1B7A69',
    opacity: 0.25,
  },
  titleBlock: {
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  headline: {
    fontFamily: 'serif',
    fontSize: 26,
    fontWeight: '800',
    color: '#1A1F1E',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: '#1B7A69',
    fontWeight: '700',
    textAlign: 'center',
  },
  stepsCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E6E8E5',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.02,
    shadowRadius: 10,
    elevation: 3,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    position: 'relative',
    paddingBottom: 22,
  },
  stepRowLast: {
    paddingBottom: 0,
  },
  verticalLine: {
    position: 'absolute',
    left: 12,
    top: 24,
    bottom: -6,
    width: 1.5,
    backgroundColor: '#E6E8E5',
    zIndex: 1,
  },
  verticalLineActive: {
    backgroundColor: '#1B7A69',
  },
  iconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F8F7F3',
    borderWidth: 1.5,
    borderColor: '#E6E8E5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    zIndex: 2,
  },
  iconContainerCompleted: {
    backgroundColor: '#E6F2EF',
    borderColor: '#1B7A69',
  },
  iconContainerActive: {
    backgroundColor: '#FDF2E9',
    borderColor: '#D67A4A',
  },
  stepDetails: {
    flex: 1,
  },
  stepText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8C9591',
    lineHeight: 20,
  },
  stepTextCompleted: {
    color: '#1A1F1E',
    fontWeight: '700',
  },
  stepTextActive: {
    color: '#D67A4A',
    fontWeight: '700',
  },
  helperText: {
    fontSize: 11,
    color: '#8C9591',
    fontWeight: '500',
    marginTop: 2,
  },
  helperTextCompleted: {
    color: '#6B7370',
  },
  helperTextActive: {
    color: '#D67A4A',
  },
});
