import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FAF8F4',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FAF8F4',
    padding: 24,
  },
  errorText: {
    fontSize: 16,
    color: '#6B7370',
    marginBottom: 24,
    textAlign: 'center',
  },
  backBtn: {
    backgroundColor: '#1A6B5A',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 100,
  },
  backBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  topBar: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E2D9',
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    padding: 4,
  },
  topBarTitle: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  heroContainer: {
    height: 200,
    backgroundColor: '#E8E2D9',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  placeholderImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeContainer: {
    paddingHorizontal: 24,
    marginTop: -20,
    alignItems: 'flex-start',
  },
  statusBadge: {
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 6,
    elevation: 3,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  propertyInfo: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
  },
  propertyName: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 8,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationText: {
    fontSize: 14,
    color: '#6B7370',
    marginLeft: 6,
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 20,
    marginHorizontal: 24,
    marginBottom: 20,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  cardHeader: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#1A1F1E',
    letterSpacing: 1,
  },
  divider: {
    height: 1,
    backgroundColor: '#E8E2D9',
    marginVertical: 12,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  infoLabel: {
    fontSize: 14,
    color: '#6B7370',
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1F1E',
  },
  payoutValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A6B5A',
  },
  totalLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1F1E',
  },
  guestRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  guestAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#D4704A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  guestAvatarText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 18,
  },
  guestMeta: {
    flex: 1,
  },
  guestName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  guestSub: {
    fontSize: 12,
    color: '#6B7370',
    marginTop: 2,
  },
  messageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A6B5A',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 100,
  },
  messageBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 6,
  },
  specialRequestBox: {
    borderLeftWidth: 3,
    borderLeftColor: '#D4704A',
    paddingLeft: 12,
    marginVertical: 4,
  },
  specialRequestText: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#6B7370',
    lineHeight: 20,
  },
  footer: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  referenceText: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: '#6B7370',
    marginTop: 4,
  },
});
