import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF8F4',
  },
  topBar: {
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FAF8F4',
    paddingHorizontal: 24,
  },
  topBarTitle: {
    fontSize: 28,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
  },
  topBarSubtitle: {
    fontSize: 14,
    color: '#6B7370',
    marginTop: 4,
  },
  bellButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  badge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#D4704A',
    width: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 'bold',
  },
  tabsContainer: {
    height: 48,
    flexDirection: 'row',
    backgroundColor: '#FAF8F4',
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E2D9',
    marginBottom: 16,
  },
  tabButton: {
    marginRight: 24,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 4,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabButtonActive: {
    borderBottomColor: '#1A6B5A',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7370',
  },
  tabTextActive: {
    color: '#1A6B5A',
    fontWeight: 'bold',
  },
  scrollContent: {
    paddingBottom: 120,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 80,
  },
  emptyText: {
    fontSize: 16,
    color: '#6B7370',
    marginTop: 12,
    fontWeight: '600',
  },
  // Card Styles
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 20,
    marginHorizontal: 24,
    marginBottom: 24,
    shadowColor: '#1A1F1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E8E2D9',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  headerDetails: {
    flex: 1,
  },
  guestName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1F1E',
  },
  guestsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  guestsCount: {
    fontSize: 13,
    color: '#6B7370',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 100,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  propertyDetails: {
    marginBottom: 16,
  },
  propertyName: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#1A1F1E',
    marginBottom: 6,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bookingDates: {
    fontSize: 14,
    color: '#6B7370',
  },
  refBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F5F0',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E8E2D9',
    marginBottom: 16,
  },
  refLabel: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#6B7370',
    letterSpacing: 1,
    marginBottom: 4,
  },
  refValue: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: '#1A1F1E',
    fontWeight: '700',
  },
  copyBtn: {
    padding: 8,
  },
  specialRequestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  specialRequestText: {
    fontSize: 13,
    color: '#6B7370',
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E8E2D9',
    paddingTop: 16,
  },
  footerLeft: {
    flexDirection: 'row',
    gap: 8,
  },
  messageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1A6B5A',
    borderRadius: 100,
    paddingHorizontal: 12,
    height: 36,
  },
  messageBtnText: {
    color: '#1A6B5A',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  detailsBtn: {
    backgroundColor: '#1A6B5A',
    borderRadius: 100,
    paddingHorizontal: 12,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  amountText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1F1E',
  },
  // FAB
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#D4704A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#D4704A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
});
